SELECT
    f.film_id,
    f.title AS FilmTitle,
    f.replacement_cost, -- The cost of replacing one copy of the film
    SUM(p.amount) AS TotalRentalRevenue, -- Total income generated by all rentals of this film
    (SUM(p.amount) - f.replacement_cost) AS EstimatedProfit -- (Total Revenue - Replacement Cost)
FROM
    film AS f
LEFT JOIN -- LEFT JOIN to include films that might not have been rented yet (their profit would be negative replacement_cost)
    inventory AS i ON f.film_id = i.film_id
LEFT JOIN
    rentat AS r ON i.inventory_id = r.inventory_id
LEFT JOIN
    payment AS p ON r.rental_id = p.rental_id
GROUP BY
    f.film_id, -- Group by film_id to ensure unique film aggregation
    f.title,
    f.replacement_cost
ORDER BY
    EstimatedProfit DESC
LIMIT 20; -- Display the top 20 most profitable films