SELECT
    co.country AS CustomerCountry,
    ci.city AS CustomerCity,
    f.rating AS FilmMPAARating, -- The MPAA rating of the film
    COUNT(r.rental_id) AS TotalRentalsForRatingInLocation, -- How many times films of this rating were rented in this location
    SUM(p.amount) AS TotalRevenueForRatingInLocation      -- Total revenue generated by films of this rating in this location
FROM
    customer AS c
JOIN
    address AS a ON c.address_id = a.address_id
JOIN
    city AS ci ON a.city_id = ci.city_id
JOIN
    country AS co ON ci.country_id = co.country_id
JOIN
    rentat AS r ON c.customer_id = r.customer_id
JOIN
    inventory AS i ON r.inventory_id = i.inventory_id
JOIN
    film AS f ON i.film_id = f.film_id
JOIN
    payment AS p ON r.rental_id = p.rental_id -- Link to payment to get revenue
GROUP BY
    co.country,
    ci.city,
    f.rating
ORDER BY
    CustomerCountry ASC,
    CustomerCity ASC,
    TotalRentalsForRatingInLocation DESC; -- Order to see the most popular ratings for each location first