SELECT
    co.country AS CustomerCountry,
    ci.city AS CustomerCity,
    cat.name AS FilmCategory,
    COUNT(r.rental_id) AS TotalRentalsInLocationCategory, -- How many times this category was rented in this location
    SUM(p.amount) AS TotalRevenueInLocationCategory      -- Total revenue generated by this category in this location
FROM
    customer AS c
JOIN
    address AS a ON c.address_id = a.address_id
JOIN
    city AS ci ON a.city_id = ci.city_id
JOIN
    country AS co ON ci.country_id = co.country_id
JOIN
    rentat AS r ON c.customer_id = r.customer_id
JOIN
    inventory AS i ON r.inventory_id = i.inventory_id
JOIN
    film AS f ON i.film_id = f.film_id
JOIN
    film_category AS fc ON f.film_id = fc.film_id
JOIN
    category AS cat ON fc.category_id = cat.category_id
JOIN
    payment AS p ON r.rental_id = p.rental_id -- Link to payment to get revenue
GROUP BY
    co.country,
    ci.city,
    cat.name
ORDER BY
    CustomerCountry ASC,
    CustomerCity ASC,
    TotalRentalsInLocationCategory DESC; -- Order to see the most popular categories for each location first